geo-builder:
  build: .
  environment:
    PROJ_VERSION: "4.9.3"
    GDAL_VERSION: "2.1.3"
    GEOS_VERSION: "3.6.1"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
    STACK: "heroku-16"
    S3_BUCKET: "aed-heroku-geo-buildpack"
  command: bash -c './geo-build'
